### ISSUE TITLE
convert pgp ed25519 key to ssh ed25519 key format?

### ISSUE THREAD

**Issue by jcolson** [paulmillr/ed25519-keygen#1]
is there a way that one could convert pgp ed25519 key to ssh ed25519 key format with this library?  is there any interoperability between the ssh and pgp exports?

**Comment by paulmillr** [comment]
You can use pgp.decodeSecretKey to convert private key to bigints, and then use those bigints in ssh keygen.

**Comment by jcolson** [comment]
One follow on question to this issue. Is there a way to create a PGP key by loading an ed25519 subkey from a file created by gpg's --export-secret-subkeys ?  That can then, subsequently have decodeSecretKey called on it?

Thanks for your help!

**Comment by paulmillr** [comment]
Pgp keys depend on user's name/email/generation date. Ssh keys don't depend on this information. So, not really. You can generate both keys from one entropy piece though.

**Comment by jcolson** [comment]
The last question had nothing to do with SSH;  I was just wondering if your PGP library had the ability to represent (load from a file) a GPG key/subkey that had been exported from a GPG keyring via the gpg --export-secret-subkeys ?

**Comment by paulmillr** [comment]
No such feature, also it was not a design goal.

**Comment by jcolson** [comment]
no worries, was just wondering.
