### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/ed25519-keygen#11]
Could you please publish latest version to npm.

0.4.1 version is last in npm https://www.npmjs.com/package/ed25519-keygen?activeTab=versions

**Comment by paulmillr** [comment]
npm/github does not allow me to. There is some error. I've contacted them 1-2 months ago, still not resolved.

**Comment by mahnunchik** [comment]
> npm WARN deprecated @noble/curves@0.8.3: Upgrade to 1.0.0 or higher for audited version

Maybe there is sense to publish module to namespace?

**Comment by paulmillr** [comment]
I will, as soon as it gets audited, it will be moved into `@scure`. Not noble since it's not cryptography.

As for 0.8.3 warning: if they don't fix the issue, I should remove the warning for now.

**Comment by mahnunchik** [comment]
@paulmillr could you please clarify when the library could be moved to `@scure` or be updated by current npm name?

**Comment by paulmillr** [comment]
The goal is to move under the scure name later this year.

No NPM updates until then, feel free to use your fork for now.

**Comment by paulmillr** [comment]
Any ideas on a new package name that would be under `@scure/`, if they won't allow to use `keygen`?

**Comment by mahnunchik** [comment]
Maybe `ed25519-key` or `ed25519-utils`

**Comment by paulmillr** [comment]
0.4.8 is out finally
