### ISSUE TITLE
does this lbrary supports non-hardened derivation of a public key ?

### ISSUE THREAD

**Issue by wighawag** [paulmillr/ed25519-keygen#12]
I am looking in generated keys from a parent hd key both from its private key and public key, so that the resulting keys matches

The api seems to only work on keys where the private key is known. any pointer to get non-hardened keys ?

I want something like the function `deriveFromPublicKey` in the following

`derive(parent private key).publickey = deriveFromPublicKey(public key)`

**Comment by paulmillr** [comment]
No. Non-hardened keys have reduced security, we don't support it.

**Comment by wighawag** [comment]
Thanks for the quick reply

In the mean time I managed  to get following working and now I am confused:

```
const publicOnlyKey = HDKey.fromExtendedKey(hdkey.publicExtendedKey);
const derivedFromPublic = publicOnlyKey.derive("m/0/2147483647/1").publicKey;
const derivedFromPrivate = hdkey.derive("m/0/2147483647/1").publicKey;
```

is that not supposed to work in this library ?

**Comment by paulmillr** [comment]
I don't see `fromExtendedKey` in https://github.com/paulmillr/ed25519-keygen/blob/main/src/hdkey.ts

**Comment by wighawag** [comment]
Oh sorry, I was reading the doc from there but was using  https://github.com/paulmillr/scure-bip32

So I guess for bip32 it is fine
