### ISSUE TITLE
Is it possible to implement extended private/public keys?

### ISSUE THREAD

**Issue by barthuijgen** [paulmillr/ed25519-keygen#13]
The library https://github.com/paulmillr/scure-bip32/blob/main/index.ts implements extended keys where you can do `hdkey.fromExtendedKey(master.publicExtendedKey).deriveChild(x)` 

I'm looking for this feature using `ed25519` and found this nice hdkeys implementation: https://github.com/paulmillr/ed25519-keygen/blob/main/src/hdkey.ts it looks very similar to `scure-bip32`, I've tried porting over the code from `scure-bip32` to use ed25519 but not to much success, so I figured I should just ask. Is this possible at all?

**Comment by paulmillr** [comment]
it may be possible

spec https://github.com/satoshilabs/slips/blob/master/slip-0010.md

**Comment by barthuijgen** [comment]
That page says this:

Public parent key → public child key
This function always fails for ed25519 since normal derivation is not supported.

I'm looking to be able to derive from the public extended key so this seems to me like it won't be possible for ed25519?

**Comment by paulmillr** [comment]
seems like it

**Comment by paulmillr** [comment]
FYI non-hardened keys are not secure in terms of privacy.
