### ISSUE TITLE
Update `@noble/curves` or make dependencies matching less strict

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/ed25519-keygen#15]
Hello,

I've faced with the fact that clean installation of `ed25519-keygen` module installs two versions of `@noble/hashes`.

```bash
npm install ed25519-keygen

npm list @noble/hashes

test-ed25519-keygen@1.0.0 test-ed25519-keygen
└─┬ ed25519-keygen@0.4.10
  ├─┬ @noble/curves@1.2.0
  │ └── @noble/hashes@1.3.2
  └── @noble/hashes@1.3.3
```

It is not a big problem for a single usage but produces a lot of duplicates when using many `@noble/*` and `@scure/*` libraries.

**Comment by paulmillr** [comment]
We already have it relaxed (~), but not too relaxed (^), it just needed a new release. Done! 0.4.11
