### ISSUE TITLE
Best canonical URL link back to the project?

### ISSUE THREAD

**Issue by imcotton** [paulmillr/ed25519-keygen#23]
Upon update my [gen-ssh-ed25519][cli] to adopt `micro-key-producer` **0.7**, what's the best way to apply the credit back here in its README (other than current npm naming in ascii tree chart)?

I have the following options in mind:

1. GitHub URL
1. npm URL
1. your own site page (if any)

Which option or options do you preferred? Thanks.

[cli]: https://jsr.io/@key/gen-ssh-ed25519

**Comment by paulmillr** [comment]
just put it in readme

**Comment by imcotton** [comment]
Yes on that, only need to decide which type of URL to add there.

**Comment by paulmillr** [comment]
I think people are generally looking for github links.

NPM is losing market share to things like deno and bun which may use different package managers. Also people don't casually lurk NPM much, which can't be said for github.

**Comment by imcotton** [comment]
Got it, thanks.
