### ISSUE TITLE
attempting to use ed25519-keygen to load a key created with gnupg

### ISSUE THREAD

**Issue by jcolson** [paulmillr/ed25519-keygen#4]
https://gist.github.com/jcolson/5bfa8650482cc0e31788b1d42b20fb0b

I'm attempting to use your library to load a gpg key created with gnupg (I noticed in one of your test cases you where doing something similar, but it was with a key that was generated deterministically with your tool, I assume.)  Is there something that could be changed in order to successfully load a gpg key not created using ed25519-keygen/pgp ?

**Comment by paulmillr** [comment]
> (I noticed in one of your test cases you where doing something similar, but it was with a key that was generated deterministically with your tool, I assume.)

No, it is key generated by GnuPG, we check that we generate exact same output as GPG in this test case.

> Is there something that could be changed in order to successfully load a gpg key not created using ed25519-keygen/pgp ?

That's strange key:

- there is no cv25519 key at all
- it is non-encrypted (was not supported before, I've added support for that case).

Please note, that we only implement subset of PGP spec which required to generate keys, so not all GPG messages will be sucessfully decoded.

In any case, that should work now. We've added third checksum type.
